### ISSUE TITLE
Writing tests with enzyme in react-17 fails due to camelCaseNames

### ISSUE THREAD

**Issue by MikeMcMahon** [brianzinn/react-babylonjs#132] opened 2021-05-15 17:30 UTC
We are running React-17 with react-babylonjs and writing some unit tests for various aspects of the world. 

The majority of our tests run fine (against non-jsx code) however react-17 requires PascalCase components to work correctly.  Our tests are throwing errors like 

```bash
  console.error
    Warning: <standardMaterial /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
        at standardMaterial
```

which follows up with an error as such 

```bash
Warning: The tag <standardMaterial> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
        at standardMaterial
```

Libraries we are using for testing: 

* Jest
* Enzyme

 I'm trying to find a way around this but right now calls are failing inside the enzyme Adapter which is attempting to create wrapped React Components for mounting/unmounting test purposes.  It seems enzyme + react17 does not play well with the intrinsic elements when they are named camelCase vs. PascalCase.

**Comment by brianzinn** [comment] 2021-05-15 20:28
The camelCase naming convention for intrinsic elements (host elements in renderer) does match the SVG implementation:
https://github.com/preactjs/preact/blob/master/src/jsx.d.ts#L909

PascalCase is only for react Components as you know, so not for for the "host" elements of the renderer.  The lowercase are for HTML elements (like div/span).  Are you able to render those svg elements that are in camelCase?  If so then maybe we just need to let your test environment know somehow that `react-babylonjs` has extended the global JSX.IntrinsicElements.

This project has extended IntrinsicElements to provide strong TypeScript and autocomplete support.  It looks like this:
```javascript
declare global {
    namespace JSX {
        interface IntrinsicElements {
            node: FiberNodeProps & FiberNodePropsCtor & BabylonNode<BabylonjsCoreNode>;
            transformNode: FiberTransformNodeProps & FiberTransformNodePropsCtor & BabylonNode<BabylonjsCoreTransformNode>;
            abstractMesh: FiberAbstractMeshProps & FiberAbstractMeshPropsCtor & BabylonNode<BabylonjsCoreAbstractMesh>;
            ......
        }
    }
}
```

They are generated directly from the typings in babylonjs.  You'll see it when you are editing JSX in an editor like Code.  I don't know a way to get enzyme to recognize custom elements...  Does that help?

**Comment by MikeMcMahon** [comment] 2021-05-16 15:59
ah, no cigar, still has the same error - but this makes me believe this is a lot less react-babylonjs and more of an enzyme + react thing.  I'll see if I can work it from that angle for a bit and see.  I may have to wrap the react-17 adapter (since it is unofficial while an official one is worked on).

**Comment by brianzinn** [comment] 2021-05-16 16:11
The other thing is that it’s a warning you can maybe disable?  It’s better to rely on a linting library IMO to correct those things :)

**Comment by MikeMcMahon** [comment] 2021-05-16 17:11
yeah, I was able to get jest to swallow and ignore the warnings, but the code coverage shows that none of the props or hooks are getting called (I can't test any `onCreated()` functions etc).  

I need to rethink how I'm attacking the tests now, we can probably safely close this out.  I may need to open an issue with enzyme or the react-17 adapter to figure out how they expect IntrinsicElements to be tested.

**Comment by MikeMcMahon** [comment] 2021-05-21 18:27
Just an update on this, i was able to use react-test-renderer to get the components to render-ish.  I'm finding that something in the react-reconciler is not triggering as none of the components hooks are firing (like onCreated).  It looks like this bit is owned by the `createReconciler()` which eventually uses the `ReactBabylonJSHostConfig`. 

Not sure what the disconnect is, and I have to say I'm struggling to google how one might test custom components that are resolved via a custom renderer hahah.

**Comment by brianzinn** [comment] 2021-05-21 19:54
I don't know if this is helpful.  I myself haven't done this type of testing before:
https://reactjs.org/docs/testing-recipes.html#multiple-renderers

I wonder if adding a test renderer would work for your scenario - do you need specifically the `onCreated` events to be captured or would getting the scene graph in a testable format be enough (ie: behaviour or state testing)?  Maybe you can provide some of your test scenarios.  It's quite ironic that as a generally TDD practitioner that tests were added to this project 2+ years in, but there are some very basic tests added recently and I plan to continue adding tests as new features are added, but anyway - it may give you an another idea on how you can test:
https://github.com/brianzinn/react-babylonjs/blob/master/test/render.spec.tsx
^^ those should fire onCreated callbacks (although not on Scene object). They are just very basic tests using NullEngine to verify the props are handled correctly.

**Comment by konsumer** [comment] 2021-05-21 20:49
Sorry if I'm jumping in, out of place, but I feel like this is mixing concerns a bit, and I saw this scroll by in my notifications. I worked on the the custom renderer for this project, but I am just expressing my general opinions about testing with react here, hoping it will help.

There are unit-tests (test isolated "units") and there are functional tests ("I loaded the whole thing how it should be, now I am going to verify it did what I expect"), and combinations of mocking different layers to test what you need to test, and they serve different purposes, in my opinion.

react-test-renderer/enzyme is meant to mock the DOM renderer & browser DOM API in order to test DOM-based react components. react-bablyonjs is also it's own react-renderer context and we're bound to have issues trying to test one renderer with another that is not designed for testing it. It might work, and I like @brianzinn's suggestion above with "multiple renderers", which is for sure worth a shot, and may make things easier and fit better with your current workflow, but I think the real long-term all-user answer would be to make a custom test-renderer (like the react team did for `ReactDOM.render` which may be a bit out of scope for this project.

I also am very into TDD in general, especially when I am working on a larger team. When I am working on regular react projects, I tend to test a little differently, and applying that strategy may help, here. I try to keep all my state and data in hooks & context, then test those. For components, if I really need to automate testing that the correct DOM was created, I find external user-level functional testing (like karma) works better, like "did the component output the right stuff on this web-page?" but I use these more functional tests pretty sparingly (a storybook with human eyes checking for problem areas on each component tends to work much better.) Unit-tests are great for catching code errors, and logic issues in hooks/context, but they will never be as good at "does that look right?" as a human, at least until AI improves to the point that we are using automated tests the same way I am doing functional "storybook tests".

Much like TDD trains us to restructure our non-react code to "be more testable", I think you can apply a similar approach to react stuff, instead of mocking everything that isn't easy to test (like the DOM) maybe focus on separating your tests into true unit-tests (tests hooks for different input, read context, etc) and more functional tests for how components render their input (storybook is a great way to do this, automate it, if you need to, with karma.)

**Comment by MikeMcMahon** [comment] 2021-05-21 21:06
> I don't know if this is helpful. I myself haven't done this type of testing before:
> https://reactjs.org/docs/testing-recipes.html#multiple-renderers
> 
> I wonder if adding a test renderer would work for your scenario - do you need specifically the `onCreated` events to be captured or would getting the scene graph in a testable format be enough (ie: behaviour or state testing)? Maybe you can provide some of your test scenarios. It's quite ironic that as a generally TDD practitioner that tests were added to this project 2+ years in, but there are some very basic tests added recently and I plan to continue adding tests as new features are added, but anyway - it may give you an another idea on how you can test:
> https://github.com/brianzinn/react-babylonjs/blob/master/test/render.spec.tsx
> ^^ those should fire onCreated callbacks (although not on Scene object). They are just very basic tests using NullEngine to verify the props are handled correctly.

```Qualified path resolution failed - none of the candidates can be found on the disk.``` when I try to use the createReconciler function haha.

**Comment by konsumer** [comment] 2021-05-21 21:12
@MikeMcMahon do you have a link to your code, or some subset that illustrates the issue? I'm willing to take a look.

I can't be sure how it's structured, but It helps me a lot to do everything as "dumb components" (presentational only) and keep logic & data in hooks. That way you can write simpler stories for just the dumb components, and more precise unit-tests that target individual hooks and context-changes. In react it's possible to put everything directly in big components, including logic, state, and all rendering paths, but I find it gets pretty unmanageable if it's at all complex. If I'm at the stage where "tests would probably make this easier to understand and ensure it's working" then it's also probably time to break it into lots of little (easily testable) hooks and simple dumb components (with storybook stories for them all.) When I start projects now, if I know it will end up this way, I just dev in storybook primarily, making tons of little visual tests, then make hooks (and associated unit-tests) to support it.

**Comment by MikeMcMahon** [comment] 2021-05-21 21:13
> Sorry if I'm jumping in, out of place, but I feel like this is mixing concerns a bit, and I saw this scroll by in my notifications. I worked on the the custom renderer for this project, but I am just expressing my general opinions about testing with react here, hoping it will help.
> 
> There are unit-tests (test isolated "units") and there are functional tests ("I loaded the whole thing how it should be, now I am going to verify it did what I expect"), and combinations of mocking different layers to test what you need to test, and they serve different purposes, in my opinion.
> 
> react-test-renderer/enzyme is meant to mock the DOM renderer & browser DOM API in order to test DOM-based react components. react-bablyonjs is also it's own react-renderer context and we're bound to have issues trying to test one renderer with another that is not designed for testing it. It might work, and I like @brianzinn's suggestion above with "multiple renderers", which is for sure worth a shot, and may make things easier and fit better with your current workflow, but I think the real long-term all-user answer would be to make a custom test-renderer (like the react team did for `ReactDOM.render`) which may be a bit out of scope for this project.
> 
> I also am very into TDD in general, especially when I am working on a larger team. When I am working on regular react projects, I tend to test a little differently, and applying that strategy may help, here. I try to keep all my state and data in hooks & context, then test those. For components, if I really need to automate testing that the correct DOM was created, I find external user-level functional testing (like karma) works better, like "did the component output the right stuff on this web-page?" but I use these more functional tests pretty sparingly (a storybook with human eyes checking for problem areas on each component tends to work much better.) Unit-tests are great for catching code errors, and logic issues in hooks/context, but they will never be as good at "does that look right?" as a human, at least until AI improves to the point that we are using automated tests the same way I am doing functional "storybook tests".
> 
> Much like TDD trains us to restructure our non-react code to "be more testable", I think you can apply a similar approach to react stuff, instead of mocking everything that isn't easy to test (like the DOM) maybe focus on separating your tests into true unit-tests (tests hooks for different input, read context, etc) and more functional tests for how components render their input (storybook is a great way to do this, automate it, if you need to, with karma.)

Not out of line at all to jump in, and I understand your sentiments.  There is a lot of code that's not very decomposable within the hooks that we need and want to verify does what we think it does.  Not all of it is presentation.  That is all I want to get to. I want to be able to fire up a dummy scene on a null engine, mount in one of our components that encompasses a lot of functionality, and ensure that the code paths are behaving as expected (react hooks and all).  

Of course, we plan to use frameworks like Karma to ensure components look and behave the way they are supposed to behave but we're also attempting to test the more subtle nuances (since not all bugs are obvious visual bugs).  

To that extent, it would be beneficial to test a complete rendering workflow, including all of the hooks we expect to fire to ensure that things are still running as we expect them to run.  Laying in the behavioral tests on top to ensure that when in browser things continue to work and run as we hope and expect.

**Comment by konsumer** [comment] 2021-05-21 21:16
> There is a lot of code that's not very decomposable within the hooks that we need and want to verify does what we think it does. Not all of it is presentation.

I guess this is the part i am getting at. I would strive to make that code "more testable". I know how it is, and sometimes it just isn't simple to do that, but "more testable" also means "easier to reason about" which has many benefits outside of my own testing setup (for larger teams this can be really important.)

**Comment by MikeMcMahon** [comment] 2021-05-21 21:17
> @MikeMcMahon do you have a link to your code, or some subset that illustrates the issue? I'm willing to take a look.
> 
> I can't be sure how it's structured, but It helps me a lot to do everything as "dumb components" (presentational only) and keep logic & data in hooks. That way you can write simpler stories for just the dumb components, and more precise unit-tests that target individual hooks and context-changes. In react it's possible to put everything directly in big components, including logic, state, and all rendering paths, but I find it gets pretty unmanageable if it's at all complex. If I'm at the stage where "tests would probably make this easier to understand and ensure it's working" then it's also probably time to break it into lots of little (easily testable) hooks and simple dumb components (with storybook stories for them all.) When I start projects now, if I know it will end up this way, I just dev in storybook primarily, making tons of little visual tests, then make hooks (and associated unit-tests) to support it.

this is exactly the problem, we use hooks to compose the data side of things.  Our onCreated hooks are not firing which means we can't unit test that functionality.  What happens when <mesh fromInstance> is mounted into the world and the onCreated() hook fires (which performs a lot of work in and of itself).  I can't share too much due to the fun of NDAs but we're not able to get a complete lifecycle of hooks firing and therein lays the problem! 

we have a LOT of components to isolate just the pertinent bits of things, so I can easily mount and mock just the bits that are necessary for a particular component to mount.  However, I go in and check to ensure things got "created" and mounted and setup properly (via unit testing) is where it falls apart.  Those things like `mesh` and `standardMaterial` etc are never actually run.

**Comment by MikeMcMahon** [comment] 2021-05-21 21:18
to be fair we can extract the onCreated() into functions but then I have a function to call a function and that is unnecessary refactoring really. 

especially when onCreated() may be interfacing with refs in the scene/component.  It ends up making things a little harder to reason about (needing to pass in mutableref objects or state callbacks)

**Comment by konsumer** [comment] 2021-05-21 21:27
>  I can't share too much due to the fun of NDAs

I understand. If you could reproduce the specific issue as an isolated project, I could probably help more.

> we use hooks to compose the data side of things. Our onCreated hooks are not firing which means we can't unit test that functionality. What happens when is mounted into the world and the onCreated() hook fires (which performs a lot of work in and of itself).

> to be fair we can extract the onCreated() into functions but then I have a function to call a function and that is unnecessary refactoring really.

Or split the "a lot of work in and of itself" into many hooks, which is more my point. If you can test all the things it does separately, and they work ok, isolated from the other stuff around them, you can narrow it down to "that is a bug with react-babylonjs's `onCreated` it's not firing like it should" or some other little part.

It sounds to me like you are using a lot of refs which that can make any react-testing a bit more painful, especially when  working with custom render-layers like this.

**Comment by MikeMcMahon** [comment] 2021-05-21 21:42
let me see if I can come up with a Short, Self Contained, Correct example that doesn't work! We make use of useEffects() to manage complex state interactions so being able to unit test between props changes and mount/unmount would be super helpful.  

We try to limit refs where we can, they are a bit like global state inside of a component, but they definitely have their use cases.

**Comment by konsumer** [comment] 2021-05-21 21:48
> let me see if I can come up with a Short, Self Contained, Correct example that doesn't work! 

Sounds good. I am happy to take a look.

> We make use of useEffects() to manage complex state interactions so being able to unit test between props changes and mount/unmount would be super helpful.

I think it would be useful here to see this use-case, too. We can narrow it down to what exactly causes the problem, and it definitely may be a bug with how refs or lifecycle stuff is implemented.

> We try to limit refs where we can, they are a bit like global state inside of a component, but they definitely have their use cases.

For sure. It can be the best way to work with an object in react-babylonjs, not a criticism, just a sidenote that it can make things more complicated, especially when ref doesn't mean "this DOM node".

**Comment by MikeMcMahon** [comment] 2021-05-22 00:12
OKAAAAY - I was able to get it figured out now :D - I took note of what @brianzinn linked me to finagle things a bit.  What did eventually work for me was using an `EngineCanvasContext` wrapping a `<Scene />` vs a `SceneContext` wrapping the elements themselves (I even tried to write my own `NullEngine` component which did not work at all). 
```jsx
    <EngineCanvasContext.Provider 
      value={{
        engine: engine,  // This is a null engine
        canvas: null,       // no need for a canvas 
      }}>
      <Scene>
        {children}
      </Scene>
    </EngineCanvasContext.Provider>);
```

in hindsight, this should have been a LOT more clear to me.  The piece I was missing was the react-reconciler and the importance it played in basically rendering out the intrinsic elements INTO the canvas vs. the dom.  

using `act()` plus the above I am now able to isolate a single component and render it and all of the stateful hooks and make assertions about what was created and the rest of the scene!

Thank you both so very much.

**Closed** 2021-05-22 00:33 UTC

**Comment by konsumer** [comment] 2021-05-22 01:19
@MikeMcMahon would you be willing to share your complete test apparatus? Like not any NDA'd components or anything, just the thing you wrap around your components to test them. It might be handy for people to see how to isolate these kinds of tests. While it's not really my style of testing, I do see the value, it seems much faster to quickly get an initial component complete with tests, and it's an extremely popular way to do that. It might even be useful in this project, as an import, so people can quickly test their stuff, something maybe like this:

```js
import { underTest } from 'react-babylonjs'
import MyComponent form './MyComponent'

test("My scene has a duck", async => (
  const { scene, engine } = await underTest(<MyComponent />)
  expect(scene.getMeshByName("duck")).toBeDefined()
))

```

**Comment by MikeMcMahon** [comment] 2021-05-22 15:37
We have one file basically composed as such:  `prefabScene.tsx` which gives us a prefabricated scene with just enough to be ready and renderable (though not shown here, we can override the rendering loop and only run a specific number of frames if necessary, but it wouldn't be too hard to envision where that code may live). 

```tsx
// prefabScene.tsx
import React, { useEffect, useRef, useState } from "react";
import {
  AbstractMesh,
  Nullable,
  NullEngine,
  Scene as BabylonjsScene,
  SceneSerializer,
  Vector3,
} from "@babylonjs/core";
import { Scene, EngineCanvasContext } from "react-babylonjs";

interface TestChildrenProps {
  scene: BabylonjsScene;
}
interface PrefabSceneProps {
  tests?: (scene: BabylonjsScene) => void;
  children?: React.ReactNode;
  testChildren?: (props: TestChildrenProps) => React.ReactNode;
}

export const PrefabScene: React.FC<PrefabSceneProps> = ({
                                                          tests,
                                                          children,
                                                          testChildren,
                                                        }: PrefabSceneProps) => {
  let sceneRef = useRef<Nullable<BabylonjsScene>>(null);
  let [engine, ] = useState<NullEngine>(() => new NullEngine({
    renderHeight: 256,
    renderWidth: 256,
    textureSize: 256,
    deterministicLockstep: false,
    lockstepMaxSteps: 1
  }));

  useEffect(() => {
    tests && tests(sceneRef.current!);
  }, [tests]);


  return(
    <EngineCanvasContext.Provider value={{
      engine: engine,
      canvas: null,
    }}>
      <Scene
        onSceneMount={(mount) => {
          sceneRef.current = mount.scene
        }}
      >
        <arcRotateCamera
          key={"test"}
          name={"test"}
          radius={5}
          alpha={0}
          beta={0}
          target={Vector3.Zero()}
        />
        {children}
        {testChildren &&
        testChildren({
          scene: sceneRef.current!,
        })}
      </Scene>
    </EngineCanvasContext.Provider>
  );
};

/***
 *
 * @param mesh
 */
export function serializeMesh(
  mesh: Nullable<AbstractMesh>
): [Record<string, any>, string] {
  if (!mesh) {
    throw Error("cannot serialize null mesh");
  }
  let serialized = SceneSerializer.SerializeMesh(mesh);
  return [serialized, JSON.stringify(serialized, null, 2)];
}

```

and then in another test such as `someComponent.test.tsx` we have
```tsx
// someComponent.test.tsx
describe("<SomeComponent />", () => {
  it("should render a component", (done) => {
    let renderer: ReactTestRenderer;
    act(() => {
      renderer = create(<PrefabScene key={"test"} />)
    })

    act(() => {
      renderer.update(
        <PrefabScene
          key={"test"}
          tests={(scene) => {
            expect(scene.getMeshByName("test-uuid")).toBeTruthy();
            let [serialized,] = getSerializedMesh(scene.getMeshByName("test-uuid"));
            expect(serialized).toMatchSnapshot<Record<string, any>>({
            geometries: {
              vertexData: [
                {
                  id: expect.any(String),
                },
              ],
            },
            meshes: [
              {
                geometryId: expect.any(String),
                uniqueId: expect.any(Number),
              },
            ],
          });
            // more tests in here...
          }}
          testChildren={(props) => {
            // we use testChildren here because this component has required values that 
            // can't be derived from outside of the prefab scene, but prefab also accepts children components.
            return (
              <SomeComponent
                key={"test-uuid"}
                uuid={"test-uuid"}
                name={"test-uuid"}
                position={new Vector3(0, 0, 1)}
                scene={props.scene}
              />
            );
          }}
        />
      );
    });

    act(() => {
      renderer.unmount();
      done();
    })
  });
});

```

the above is pretty basic and doesn't encompass everything we can do with the `PrefabScene` component, for our purposes we can now load a single component in and check that the react hook lifecycles are doing what we expect them to be doing.  

You might notice that the SomeComponent is taking in a Scene as a prop vs calling `useScene()` we actually had to stop using `useScene()` when we checked with `why-did-you-render` we found that `useScene()` was causing every component to re-render whenever there was a change to the scene.  Once we pulled that out the components stopped unnecessarily re-rendering.  That's not really a big deal for the purpose of the above example, but just showing one such use-case for why we have the ability to pass in child components in different ways.

**Comment by brianzinn** [comment] 2021-05-23 02:19
thanks @MikeMcMahon - also for providing your working example!  I had actually clued in before and was going to let you know about the EngineCanvasContext.Provider - that is how to connect React Native (with their useEngine and passing back the camera).  Anyway, glad that you got it all connected and figured out.  I will definitely take what you have provided there and include test cases here on the `<Scene />` component - I will get to that in 2-3 weeks, but feel free to drop a PR if you were interested.
