### ISSUE TITLE
colorPicker value not changing

### ISSUE THREAD

**Issue by kyehuelin** [brianzinn/react-babylonjs#131] opened 2021-05-06 06:48 UTC
currently running 
```
    "@babylonjs/core": "^4.2.0",
     "react-babylonjs": "^3.0.14",
```
Hi Brian, when i set the value to a given color the colorpicker is not updating to that color, it just stays red, which i guess is the default color.

```
const green = new Color3(0, 1, 0);
return (
...
      <colorPicker value={green} ... />
...
```

**Comment by brianzinn** [comment] 2021-05-07 02:08
thanks for reporting @kyehuelin .  I will investigate - have never actually used that control before :)

**Comment by brianzinn** [comment] 2021-05-07 05:01
It seems like a bug in babylonjs where it's not invalidating the control to redraw.  Here is a codesandbox to reproduce:
https://codesandbox.io/s/falling-voice-p4sjs?file=/src/App.js

Notice that the color is changing in the inspector, but not in the UI:
![image](https://user-images.githubusercontent.com/542756/117398759-d7edd880-aeb3-11eb-9c93-0b659b30bc82.png)

![image](https://user-images.githubusercontent.com/542756/117398793-e63bf480-aeb3-11eb-8293-1dcd12f59b06.png)

I cannot explain it right now :(  I tried it on a regular babylonjs playground and it works... I haven't come across before where something in the Explorer wasn't reflected in the canvas.

**Comment by brianzinn** [comment] 2021-05-07 05:07
Actually I found the reason.  It's because I do a copyFrom.
```javascript
colorPicker.value.copyFrom(Color3.Green());
```
That won't trigger the code needed to update the GUI (https://github.com/BabylonJS/Babylon.js/blob/master/gui/src/2D/controls/colorpicker.ts#L49).  I think there will be no adverse side effects if I change that to assignment.

**Comment by brianzinn** [comment] 2021-05-07 05:37
Good find - took me a bit of digging, because I was looking in the wrong place!!  Fixed in version `3.0.15`.  please re-open if it's not working.

**Closed by brianzinn** 2021-05-07 05:37 UTC
Labels: bug

**Comment by kyehuelin** [comment] 2021-05-07 09:45
Hi Brian, Ive realised that this maybe a wider issue with all Intrinsicelements values being passed as props.

for example, all the lights have a diffuse and specular, which have the same problem as colorPicker. once the value are set, there is no changing them again.

**Comment by kyehuelin** [comment] 2021-05-07 18:23
@brianzinn  added a bit more :)
