### ISSUE TITLE
Breaking changes between 3.1.11 and 3.1.13

### ISSUE THREAD

**Issue by coder89** [brianzinn/react-babylonjs#251] opened 2022-11-06 14:17 UTC
Hi,

Today I was doing a packages upgrade and discovered that 3.1.13 introduces a breaking change that isn't documented (or at least I couldn't find any info about it). All props like `position-x`, `scale-y`, etc. stopped working. Turns out that this library no longer takes care of these. Was this intentional design change (that should be documented somewhere in the release notes) or should it be treated as a bug? 

Properties without `-x` `-y` `-z` work just fine BTW.

Thanks!

**Comment by brianzinn** [comment] 2022-11-06 15:40
It was intentional. I wasn’t sure about the community impact, because it wasn’t really documented. The arcRotateCamera crashes if you change the upVector, because it has a set accessor. What I was trying to do was guide people down the right path. If you look at TransformNode the position is a serAccessor that sets an internal property. I think I’m ok to put it back - to be honest I was very surprised how many properties used set accessors.

what do you think?

**Comment by brianzinn** [comment] 2023-01-31 05:20
closing as "by design", since it follows best practices automatically.

**Closed by brianzinn** 2023-01-31 05:20 UTC
