### ISSUE TITLE
Errors when using declarative mode in typescript project

### ISSUE THREAD

**Issue by pjoe** [brianzinn/react-babylonjs#10] opened 2019-01-14 14:31 UTC
Trying to get this working in a typescript project (with CRA 2):
```typescript
const DefaultPlayground = () => (
    <Engine canvasId="sample-canvas" antialias width={400} height={300}>
        <Scene canvas={null} engine={null} scene={null}>
            <FreeCamera
                name="camera1"
                position={new Vector3(0, 5, -10)}
                target={Vector3.Zero()}
            />
            <HemisphericLight
                name="light1"
                intensity={0.7}
                direction={Vector3.Up()}
            />
            <Sphere
                name="sphere1"
                diameter={2}
                segments={16}
                position={new Vector3(0, 2, 0)}
            />
            <Ground
                name="ground1"
                width={6}
                height={6}
                subdivisions={2}
            />
        </Scene>
    </Engine>
)
```

I had to add the `canvas={null} engine={null} scene={null}` to `Scene` to get rid of first level of typescript errors, but also had to add custom definitions (to `react-app-env.d.ts`):

```typescript
import { Vector3 } from 'babylonjs'
import { FreeCamera } from "react-babylonjs";
declare module 'react-babylonjs' {
    export declare class FreeCamera extends React.Component<{
        name?: string;
        position?: Vector3;
        target?: Vector3;
    }, any> {};

    export declare class HemisphericLight extends React.Component<{
        name?: string;
        intensity?: number;
        direction?: Vector3;
    }, any> {};

    export declare class Sphere extends React.Component<{
        name?: string;
        diameter?: number;
        segments?: number;
        position?: Vector3;
    }, any> {};

    export declare class Ground extends React.Component<{
        name?: string;
        width?: number;
        height?: number;
        subdivisions?: number;
    }, any> {};

}
```

Is there some better way of making the declarative style work in a typescript project?

**Comment by brianzinn** [comment] 2019-01-14 16:47
Thanks for reporting.  I have a CRA1 TypeScript repo (https://github.com/brianzinn/create-react-app-typescript-babylonjs) using a version before the switch to becoming a renderer using 'react-reconciler'.  The typings files are now wrong as they declare everything as a strings (required by renderer for creating host components).

Can you indicate versions for 'babylonjs' and 'react-babylonjs'?  I am busy next few days, but will sort it out soon.  I think I need to generate the typings files myself.

**Comment by pjoe** [comment] 2019-01-14 17:49
Heh, was trying to figure out what was going wrong and stumbled on those string typings, that I couldn't really figure out how was working.

FWIW: here are my version info from `package.json`:
```json
{
  "name": "cra-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "23.3.12",
    "@types/node": "10.12.18",
    "@types/react": "16.7.18",
    "@types/react-dom": "16.0.11",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.3",
    "typescript": "3.2.2"
  },
  "scripts": {
    "start": "rescripts start",
    "build": "rescripts build",
    "test": "rescripts test",
    "eject": "rescripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@rescripts/cli": "^0.0.7",
    "@rescripts/rescript-use-rewire": "^0.0.3",
    "babylonjs": "^3.3.0",
    "babylonjs-gui": "^3.3.0",
    "babylonjs-loaders": "^3.3.0",
    "react-app-rewire-hot-loader": "^1.0.3",
    "react-babylonjs": "^1.0.1",
    "react-hot-loader": "^4.6.3"
  },
  "rescripts": [
    ["use-rewire", "react-app-rewire-hot-loader"]
  ]
}
```

**Comment by brianzinn** [comment] 2019-01-14 19:53
Thanks for version info.  When I sort it out will also update TypeScript CRA repo with CRA-2 and your default playground :)

**Comment by brianzinn** [comment] 2019-01-21 02:48
hi @pjoe - just wanted to drop an update that I have started on this briefly.  I ended up working both days this weekend on my real job - sort of getting crushed with work.  will try to make some time next week.  one thing that is really bothering me is that with the 'string' exports for host components and writing a different typings to satisfy TypeScript, I don't think we are going to get any tree-shaking on babylonjs 4.0 :(

**Comment by pjoe** [comment] 2019-01-21 07:45
@brianzinn Must admit I'm not too familiar with the inner workings of tree shaking, but would expect it to happen after transpilation from ts to js (and thus not be affected by typings). Will have to test out how it behaves.

**Comment by brianzinn** [comment] 2019-01-21 07:59
It is not affected by the typings, but by the references which are just strings for the host components.  Anyway, it's a separate issue.  Still want to get this working in TypeScript :)  So, will sort this out and then see about that after.  Cheers.

**Comment by brianzinn** [comment] 2019-01-27 04:48
I have split the Fiber{Class}Props into a separate file, so we could now nearly do:
```jsx
import { Vector3 } from 'babylonjs'
import { FiberFreeCameraProps, FiberHemisphericLightProps, FiberMeshProps } from "react-babylonjs";
declare module 'react-babylonjs' {
    export declare class FreeCamera extends React.Component<FiberFreeCameraProps, any> {};

    export declare class HemisphericLight extends React.Component<FiberHemisphericLightProps, any>{};

    export declare class Sphere extends React.Component<FiberMeshProps, any> {};

    export declare class Ground extends React.Component<FiberMeshProps, any> {};
}
```
That typings file when ready could just overwrite `/dist/types/generatedCode.d.ts`

Additionally, as you likely noticed, the constructor properties are missing (ie: segments on Sphere --> https://github.com/brianzinn/react-babylonjs/blob/master/src/generatedCode.ts#L3745).  Those are now dynamically created from props via the static `CreateInfo.parameters`;  Properties like `options` are flattened out like those from Meshbuilder constructor arguments.  Let me think about that for a bit as I want to make the code smaller in the process.

**Comment by brianzinn** [comment] 2019-02-07 06:20
I have simply too much work at the moment to be able to do this before April.  I would suggest you use version 0.4.6 as that should work, although with less features.  I will start working on this slowly - I want to redo the design of the project for Tree Shaking, so will combine that effort and fix your issue at the same time.  Thanks for your patience.

**Comment by pjoe** [comment] 2019-02-07 07:44
@brianzinn thanks, I've also been a bit preoccupied lately - found some issues with the blender gltf exporter, that I'm slowly fixing (sometimes vector (and matrix) math is tricky to get right)

Anyway I also played a bit with tree shaking in babylon 4 (using webpack bundle analyzer) - it's quite cool when it works correctly. If I find some time on my hands, I'll try and see what it would take to get this project updated to work with the later 4.0.0-alpha builds

**Comment by brianzinn** [comment] 2019-02-24 03:31
`ts-morph` project added support for union types (https://github.com/dsherret/ts-morph/issues/529), so I'm going to add the correct .d.ts now that the npm is out.  It will be a while though, I'm super busy for now and this can be worked around.

**Comment by promontis** [comment] 2019-08-22 10:29
@brianzinn any update on this? would love to get this working with Typescript!

**Comment by brianzinn** [comment] 2019-08-23 06:39
@promontis - thanks for your interest in the project. I actually just fired this up again recently and TypeScript integration is an absolute must-have.  I got a big PR #25 a few weeks back and I have been working on integrating it cleanly first - it's taken a bunch of time already (I stubbornly want typescript to keep building in strict mode)!  I switched over to the new 4.1 alpha versions and their ES6 is a separate package `@babylonjs/core` instead of `babylonjs` (not using Legacy/legacy), so that is another relatively big change for the generator code.  The types then depending on the package you are using will mismatch in my export.  What I have started to do is move over to the new libraries, since the original are essentially legacy.

Are you using the new `@babylonjs/core` (or which version)?
Can you show error messages you are getting?

I'll spin up a CRA3 TypeScript project this weekend and try to get it going.

**Comment by brianzinn** [comment] 2019-09-15 23:08
This is running on a TypeScript CRA project now on a branch - working to get it merged after I fix a few more things.  One main change to get it working was to add `JSX.IntrinsicTypes`.  There will be a few breaking changes as it is new in other ways, so I need to update all the docs as well...

**Comment by brianzinn** [comment] 2019-09-23 19:52
@pjoe what is on master branch now works.  Sorry it fell through the cracks, but there will be a major bump on next NPM.  Here is a working reproduction of current TypeScript demo repo from (`https://github.com/brianzinn/create-react-app-typescript-babylonjs/blob/b839cadfca6d69d05a1a1f5f4eef2312e116af27/babylonjs-site/src/containers/home/index.tsx`) written to a new CRA3 project:
```tsx
import React, { useCallback } from 'react';
import "@babylonjs/core/Physics/physicsEngineComponent"
import { Vector3, PhysicsImpostor, Mesh } from '@babylonjs/core';
import { CannonJSPlugin } from '@babylonjs/core/Physics/Plugins'
import { Scene, Engine, withBabylonJS } from 'react-babylonjs';

import './App.css';

import * as CANNON from 'cannon';
window.CANNON = CANNON;

const EngineWithContext = withBabylonJS(Engine);
const gravityVector = new Vector3(0, -9.81, 0);
let sphere: Mesh | null = null;

const onButtonClicked = () => {
  if (sphere) {
    sphere.physicsImpostor!.applyImpulse(
      new Vector3(0, 10, 0), sphere.getAbsolutePosition()
    )
  }
}

const App: React.FC = () => {

  const sphereRef = useCallback(node => {
    sphere = node.hostInstance;
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <p>
          BabylonJS + @babylonjs/react
        </p>
        <EngineWithContext antialias={true} adaptToDeviceRatio={true} canvasId="sample-canvas">
          <Scene enablePhysics={[gravityVector, new CannonJSPlugin()]}>
            
            <arcRotateCamera name="arc" target={ new Vector3(0, 1, 0) }
                  alpha={-Math.PI / 2} beta={(0.5 + (Math.PI / 4))}
                  radius={4} minZ={0.001} wheelPrecision={50}
                  lowerRadiusLimit={8} upperRadiusLimit={20} upperBetaLimit={Math.PI / 2}
                  />
            <hemisphericLight name='hemi' direction={new Vector3(0, -1, 0)} intensity={0.8} />
            <directionalLight name="shadow-light" setDirectionToTarget={[Vector3.Zero()]} direction={Vector3.Zero()} position = {new Vector3(-40, 30, -40)}
              intensity={0.4} shadowMinZ={1} shadowMaxZ={2500}>
              <shadowGenerator mapSize={1024} useBlurExponentialShadowMap={true} blurKernel={32}
                shadowCasters={["sphere1", "dialog"]} forceBackFacesOnly={true} depthScale={100}
                />
            </directionalLight>
            <sphere ref={sphereRef} name="sphere1" diameter={2} segments={16} position={new Vector3(0, 2.5, 0)}>
              <physicsImpostor type={PhysicsImpostor.SphereImpostor} _options={{
                  mass: 1,
                  restitution: 0.9
              }} />
              <plane name="dialog" size={2} position={new Vector3(0, 1.5, 0)}>
                <advancedDynamicTexture name="dialogTexture" height={1024} width={1024} createForParentMesh={true}>
                  <rectangle name="rect-1" height={0.5} width={1} thickness={12} cornerRadius={12}>
                      <rectangle>
                        <babylon-button name="close-icon" background="green" onPointerDownObservable={onButtonClicked} >
                          <textBlock text={'\uf00d click me'} fontFamily="FontAwesome" fontStyle="bold" fontSize={200} color="white" />
                        </babylon-button>
                      </rectangle>
                  </rectangle>
                </advancedDynamicTexture>
              </plane>
            </sphere>
            
            <ground name="ground1" width={12} height={12} subdivisions={2} receiveShadows={true}>
              <physicsImpostor type={PhysicsImpostor.BoxImpostor} _options={{
                  mass: 0,
                  restitution: 0.9
              }} />
            </ground>
          </Scene>
        </EngineWithContext>
      </header>
    </div>
  );
}

export default App;
```

Going to close issue.  When there is a v2.0 on NPM then above will run.

**Closed by brianzinn** 2019-09-23 19:52 UTC
Labels: in progress
