### ISSUE TITLE
The hostInstance can't be recognized as Mesh

### ISSUE THREAD

**Issue by vimcaw** [brianzinn/react-babylonjs#35] opened 2020-01-17 07:45 UTC
I want to generate an SCG Object from a mesh but get an error.

Code: 
```js
const ref = useCallback(node => {
  if (node) {
    console.log(node.hostInstance);
    const csg = CSG.FromMesh(node.hostInstance);
  }
}, []);

if (wallPath) {
  // noinspection RequiredAttributes
  return (
    <extrudePolygon
      ref={ref}
      name='wall'
      shape={wallPath}
    />
  )
} else {
  return null
}
```

It throws an error:

```console
Uncaught BABYLON.CSG: Wrong Mesh type, must be BABYLON.Mesh
```

Print the node.hostInstance by console.log:

```console
t {state: "", metadata: null, reservedDataStore: null, doNotSerialize: false, _isDisposed: false, …}
onBeforeRenderObservable: (...)
onBeforeBindObservable: (...)
onAfterRenderObservable: (...)
onBeforeDrawObservable: (...)
morphTargetManager: (...)
source: (...)
isUnIndexed: (...)
_isMesh: (...)
hasLODLevels: (...)
geometry: (...)
isBlocked: (...)
areNormalsFrozen: (...)
_positions: (...)
facetNb: (...)
partitioningSubdivisions: (...)
partitioningBBoxRatio: (...)
mustDepthSortFacets: (...)
facetDepthSortFrom: (...)
isFacetDataEnabled: (...)
visibility: (...)
material: (...)
receiveShadows: (...)
hasVertexAlpha: (...)
useVertexColors: (...)
computeBonesUsingShaders: (...)
numBoneInfluencers: (...)
applyFog: (...)
layerMask: (...)
collisionMask: (...)
collisionGroup: (...)
lightSources: (...)
skeleton: (...)
scaling: (...)
useBones: (...)
isAnInstance: (...)
_effectiveMesh: (...)
checkCollisions: (...)
collider: (...)
billboardMode: (...)
preserveParentRotationForBillboard: (...)
infiniteDistance: (...)
position: (...)
rotation: (...)
rotationQuaternion: (...)
forward: (...)
up: (...)
right: (...)
absolutePosition: (...)
isWorldMatrixFrozen: (...)
nonUniformScaling: (...)
parent: (...)
animationPropertiesOverride: (...)
behaviors: (...)
worldMatrixFromCache: (...)
state: ""
metadata: null
reservedDataStore: null
doNotSerialize: false
_isDisposed: true
animations: []
_ranges: {}
onReady: null
_isEnabled: true
_isParentEnabled: true
_isReady: true
_currentRenderId: 0
_parentUpdateId: -1
_childUpdateId: 5
_waitingParentId: null
_cache: {parent: undefined, localMatrixUpdated: false, position: e, scaling: e, rotation: e, …}
_parentNode: null
_children: null
_worldMatrix: e {_isIdentity: true, _isIdentityDirty: false, _isIdentity3x2: false, _isIdentity3x2Dirty: true, updateFlag: 189, …}
_worldMatrixDeterminant: 0
_worldMatrixDeterminantIsDirty: true
_sceneRootNodesIndex: -1
_animationPropertiesOverride: null
_isNode: true
onDisposeObservable: e {_observers: Array(0), _eventState: e, _onObserverAdded: null}
_onDisposeObserver: null
_behaviors: []
name: "wall"
id: "wall"
_scene: Scene {rootNodes: Array(1), cameras: Array(0), lights: Array(0), meshes: Array(1), skeletons: Array(0), …}
uniqueId: 15
_forward: e {x: 0, y: 0, z: 1}
_forwardInverted: e {x: 0, y: 0, z: -1}
_up: e {x: 0, y: 1, z: 0}
_right: e {x: 1, y: 0, z: 0}
_rightInverted: e {x: -1, y: 0, z: 0}
_position: e {x: 0, y: 0, z: 0}
_rotation: e {x: 0, y: 0, z: 0}
_rotationQuaternion: null
_scaling: e {x: 1, y: 1, z: 1}
_isDirty: false
_transformToBoneReferal: null
_billboardMode: 0
_preserveParentRotationForBillboard: false
scalingDeterminant: 1
_infiniteDistance: false
ignoreNonUniformScaling: false
reIntegrateRotationIntoRotationQuaternion: false
_poseMatrix: e {_isIdentity: true, _isIdentityDirty: false, _isIdentity3x2: true, _isIdentity3x2Dirty: false, updateFlag: 179, …}
_localMatrix: e {_isIdentity: false, _isIdentityDirty: true, _isIdentity3x2: false, _isIdentity3x2Dirty: true, updateFlag: 188, …}
_usePivotMatrix: false
_absolutePosition: e {x: 0, y: 0, z: 0}
_pivotMatrix: e {_isIdentity: true, _isIdentityDirty: false, _isIdentity3x2: true, _isIdentity3x2Dirty: false, updateFlag: 174, …}
_postMultiplyPivotMatrix: false
_isWorldMatrixFrozen: false
_indexInSceneTransformNodesArray: -1
onAfterWorldMatrixUpdateObservable: e {_observers: Array(0), _eventState: e, _onObserverAdded: null}
_nonUniformScaling: false
_internalAbstractMeshDataInfo: _t {_hasVertexAlpha: false, _useVertexColors: true, _numBoneInfluencers: 4, _applyFog: true, _receiveShadows: false, …}
cullingStrategy: 0
onCollideObservable: e {_observers: Array(0), _eventState: e, _onObserverAdded: null}
onCollisionPositionChangeObservable: e {_observers: Array(0), _eventState: e, _onObserverAdded: null}
onMaterialChangedObservable: e {_observers: Array(0), _eventState: e}
definedFacingForward: true
_occlusionQuery: null
_renderingGroup: null
alphaIndex:
1.7976931348623157
e+308
isVisible: true
isPickable: true
showSubMeshesBoundingBox: false
isBlocker: false
enablePointerMoveEvents: false
renderingGroupId: 0
_material: null
outlineColor: e {r: 1, g: 0, b: 0}
outlineWidth: 0.02
overlayColor: e {r: 1, g: 0, b: 0}
overlayAlpha: 0.5
useOctreeForRenderingSelection: true
useOctreeForPicking: true
useOctreeForCollisions: true
alwaysSelectAsActiveMesh: false
doNotSyncBoundingInfo: false
actionManager: null
_meshCollisionData: dt {_checkCollisions: false, _collisionMask: -1, _collisionGroup: -1, _collider: null, _oldPositionForCollisions: e, …}
ellipsoid: e {x: 0.5, y: 1, z: 0.5}
ellipsoidOffset: e {x: 0, y: 0, z: 0}
edgesWidth: 1
edgesColor: e {r: 1, g: 0, b: 0, a: 1}
_edgesRenderer: null
_masterMesh: null
_boundingInfo: e {_isLocked: false, boundingBox: e, boundingSphere: e}
_renderId: 0
_intersectionsInProgress: []
_unIndexed: false
_lightSources: []
_waitingData: {lods: null, actions: null, freezeWorldMatrix: null}
_bonesTransformMatrices: null
onRebuildObservable: e {_observers: Array(0), _eventState: e, _onObserverAdded: null}
_onCollisionPositionChange: ƒ (e, t, r)
_internalMeshDataInfo: Dt {_areNormalsFrozen: false, _source: null, meshMap: null, _preActivateId: -1, _LODLevels: Array(0), …}
delayLoadState: 0
instances: []
_creationDataStorage: null
_geometry: null
_instanceDataStorage: St {visibleInstances: {…}, batchCache: It, instancesBufferSize: 2048, hardwareInstancedRendering: true}
_effectiveMaterial: null
_shouldGenerateFlatShading: false
_originalBuilderSideOrientation: 0
overrideMaterialSideOrientation: null
subMeshes: []
__proto__: t
```

**Comment by brianzinn** [comment] 2020-01-17 16:41
Thanks for reporting.  My first thought is that it's an `AbstractMesh`?
https://github.com/BabylonJS/Babylon.js/blob/f341e71f8b4eb069d6fc08e93858519e28916594/src/Meshes/csg.ts#L427
I'll build a reproduction when I get to a computer.  Should have a solution tomorrow - I use CSG a lot :)

**Comment by vimcaw** [comment] 2020-01-18 09:29
Thanks for your work, I note the document says that `extrudepolygon ` will return a Mesh: https://doc.babylonjs.com/api/classes/babylon.polygonbuilder#extrudepolygon

**Comment by brianzinn** [comment] 2020-01-19 05:41
I have confirmed that on the regular playground extrudePolygon does return an `instanceof Mesh` and can confirm this is a bug in this repository (or in the imports/references).  I made a storybook story and see the same behaviour, but at least now have a full reproduction...  so, can confirm this issue you are seeing:
```jsx
import React, { useCallback } from 'react'
import { storiesOf } from '@storybook/react'
import '@babylonjs/inspector'
import { Engine, Scene } from '../../../dist/react-babylonjs.es5'
import { Vector3, Color3, CSG, Mesh as RootMesh } from '@babylonjs/core'
import { Mesh } from '@babylonjs/core/Meshes/mesh'
import * as Earcut from 'earcut';
import '../../style.css'

//Polygon shape in XoZ plane
var starPath = [ 
    new Vector3(4, 0, -4), 
    new Vector3(2, 0, 0), 
    new Vector3(5, 0, 2), 
    new Vector3(1, 0, 2), 
    new Vector3(-5, 0, 5), 
    new Vector3(-3, 0, 1), 
    new Vector3(-4, 0, -4), 
    new Vector3(-2, 0, -3), 
    new Vector3(2, 0, -3)
];

//Holes in XoZ plane
var holes = [
    [
        new Vector3(1, 0, -1),
        new Vector3(1.5, 0, 0),
        new Vector3(1.4, 0, 1),
        new Vector3(0.5, 0, 1.5)
    ], [
        new Vector3(0, 0, -2),
        new Vector3(0.5, 0, -1),
        new Vector3(0.4, 0, 0),
        new Vector3(-1.5, 0, 0.5)
    ]
];

const Shapes = () => {
    const ref = useCallback(node => {
        if (node) {
            console.log(node.hostInstance);
            console.log(node.hostInstance instanceof Mesh)
            console.log(node.hostInstance instanceof RootMesh)
            // const csg = CSG.FromMesh(node.hostInstance);
        }
    }, []);
    
    return (
        <Engine antialias adaptToDeviceRatio canvasId='babylonJS'>
            <Scene>
                <arcRotateCamera name='camera1' alpha={1/4 * Math.PI} beta={1/4 * Math.PI} radius={20.0} target={Vector3.Zero()} minZ={0.001} />
                <hemisphericLight name='light1' intensity={0.7} direction={Vector3.Up()} />
                <extrudePolygon
                    ref={ref}
                    name='wall'
                    holes={holes}
                    shape={starPath}
                    depth={2}
                    sideOrientation= {Mesh.DOUBLESIDE}
                    earcutInjection={Earcut}
                >
                    <standardMaterial name='starMaterial' diffuseColor={Color3.Green()} specularColor={Color3.Black()} />
                </extrudePolygon>
            </Scene>
        </Engine>
    )
}

export default storiesOf('Babylon Basic', module)
  .add('Shapes', () => (
    <div style={{ flex: 1, display: 'flex' }}>
      <Shapes />
    </div>
  ))
```

Print `false`, `false`, so explains why CSG is failing. I updated the reconciler and also it's not an `instanceof Mesh` what is returned (https://github.com/brianzinn/react-babylonjs/blob/master/src/ReactBabylonJSHostConfig.ts#L293), so I will need a bit more time to investigate.  Will try to make some time tomorrow after a road trip...
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/542756/72675579-472f8700-3a3b-11ea-9b78-1e4b2a30aeb2.png">

**Comment by brianzinn** [comment] 2020-01-19 05:50
Here is the PG for reference working as expected (although it's not using ES6 `@babylonjs/core`):
https://playground.babylonjs.com/#4G18GY#132

**Comment by brianzinn** [comment] 2020-01-20 06:05
Looks like there is nothing wrong with the ES6 library.  I followed the steps here to create a simple project (https://doc.babylonjs.com/features/es6_support).  Set this as index.js:

```javascript
import { Engine } from "@babylonjs/core/Engines/engine";
import { Scene } from "@babylonjs/core/scene";
import { Vector3 } from "@babylonjs/core/Maths/math";
import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera";
import { HemisphericLight } from "@babylonjs/core/Lights/hemisphericLight";
import { Mesh } from "@babylonjs/core/Meshes/mesh";
import * as Earcut from 'earcut'
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder"
import { CSG } from '@babylonjs/core'
// Required side effects to populate the Create methods on the mesh class. Without this, the bundle would be smaller but the createXXX methods from mesh would not be accessible.
import "@babylonjs/core/Meshes/meshBuilder";

const canvas = document.getElementById("renderCanvas");
const engine = new Engine(canvas);
var scene = new Scene(engine);
var camera = new ArcRotateCamera("camera1", 1/4 * Math.PI, 1/4 * Math.PI, 24, Vector3.Zero(), scene);
camera.attachControl(canvas, true);

var light = new HemisphericLight("light1", new Vector3(0, 1, 0), scene);
light.intensity = 0.7;

//Polygon shape in XoZ plane
var shape = [ 
    new Vector3(4, 0, -4), 
    new Vector3(2, 0, 0), 
    new Vector3(5, 0, 2), 
    new Vector3(1, 0, 2), 
    new Vector3(-5, 0, 5), 
    new Vector3(-3, 0, 1), 
    new Vector3(-4, 0, -4), 
    new Vector3(-2, 0, -3), 
    new Vector3(2, 0, -3)
];

//Holes in XoZ plane
var holes = [];
holes[0] = [ new Vector3(1, 0, -1),
 new Vector3(1.5, 0, 0),
 new Vector3(1.4, 0, 1),
 new Vector3(0.5, 0, 1.5)
];
holes[1] = [
 new Vector3(0, 0, -2),
 new Vector3(0.5, 0, -1),
 new Vector3(0.4, 0, 0),
 new Vector3(-1.5, 0, 0.5)
];

var polygon = MeshBuilder.ExtrudePolygon("polygon", {shape:shape, holes, depth: 2 }, scene, Earcut);

console.log('isMesh', polygon instanceof Mesh)

const csg = CSG.FromMesh(polygon)
const clone = csg.toMesh("clone")
clone.position.y += 6

// Render every frame
engine.runRenderLoop(() => {
    scene.render();
});
```

![image](https://user-images.githubusercontent.com/542756/72702341-2fbdd000-3b07-11ea-8425-35ddc00eff15.png)

This works on `@babylojnjs/core@4.0.3` So, I have a bug to figure out...  just no time right now to dig into it, but have narrowed it down!! :)

**Comment by vimcaw** [comment] 2020-01-20 15:29
Nice works! I will test it recently.

**Comment by brianzinn** [comment] 2020-02-04 17:20
I didn't figure it out yet, but wanted to capture a reproduction of the issue with logs that also point out the issue and if anybody else wanted to try to track it down.
https://github.com/brianzinn/react-babylonjs/tree/instance-errors-extrudeshape

**Comment by brianzinn** [comment] 2020-03-16 16:57
I think I got it figured out - managed to get some time yesterday.  I'll try to get it merged and with above example working this weekend :)

**Comment by brianzinn** [comment] 2020-03-19 06:06
fixed!
https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--extrude-shapes-csg

**Closed** 2020-03-19 06:06 UTC

**Comment by vimcaw** [comment] 2020-03-19 06:13
Great work! Thank you again! 😀
